### ISSUE TITLE
Deploy latest competition code to robot.

### ISSUE THREAD

**Issue by gbuckholtz** [Machine-Mavericks/FRC-2023#60]
We have a new version [in competition branch](https://github.com/Machine-Mavericks/FRC-2023/tree/v2.0-LondonComp)

- [x] Deploy this branch to the robot
- [ ] Verify that the branch and commit id are displayed in Shuffleboard.  Talk to @lilyen06 if you can't find it.
- [x] Make a copy of the deployed code on the microSD card in the pit.  Talk to @DanDjuric or @frotle (Jeff) about how to do it using Etcher.
- [x] RETURN THE CARD TO THE PIT!!!!
- [x] return the original card to the roboRIO

**Comment by lilyen06** [comment]
This has been done (:

**Comment by lilyen06** [comment]
Dan has the SD cards, not sure if they are in the pit

**Comment by frotle** [comment]
The SD Card is in the Computer stuff drawer, left side in a case marked Robot.  I'll be in tomorrow night and will backup the SD card in the pit if needed.

Jeff

**Comment by DanDjuric** [comment]
The "v2.0-LondonComp" branch as synced and loaded on two SD cards (One in the robot, the other back in the pit).
We also loaded another SD card with the same version but a gripper timing change that did not work any different which is in my bag. Tonight, this one will also be changed back to the same as the other two and left in the pit.
Note:   balenaEtcher will allow the copy of a smaller to larger SD card, but not the other way around, but it does allow flashing from a file "FRC_roboRIO2_2023_v3.2.img" which tested fine. Anyway, all three SD's are flashed so from here on in, we can simply deploy any code version we want on them and no need for balenaEtcher.

**Comment by frotle** [comment]
Thanks Dan & all - much apprecaited.

**Comment by gbuckholtz** [comment]
The only sanity check I would like to see, is to verify that the branch and commit id is showing up in shuffleboard.
We should be seeing:
Commit:  0473ff4
Branch: v2.0-LondonComp

**Comment by gbuckholtz** [comment]
I think that I didn't need to make a separate branch for v2.0-LondonComp.  GitHub made a branch for me when I tagged the release.
In the future we will use the one that was made by git, since it is a bit more flexible and conforms to the release process in GitHub.  [V2.1](https://github.com/Machine-Mavericks/FRC-2023/tree/v2.1)

**Comment by DanDjuric** [comment]
Will need to double check on this tonight, but I believe the Branch was correct, however it had a different commit.
This is what I believe was deployed:
![2023-03-16 14_17_39-Grabber java - FRC-2023 - Visual Studio Code](https://user-images.githubusercontent.com/122225008/225717036-25f18d4b-bf45-48c8-a344-b427ba769957.png)

**Comment by DanDjuric** [comment]
This one has a very similar commit, but it's name is just V2.1
Just want to make sure we have the right set of code on the robot, but at least it was operating as expected.
![2023-03-16 14_18_20-Grabber java - FRC-2023 - Visual Studio Code](https://user-images.githubusercontent.com/122225008/225717136-b321a60e-0cac-4eb8-83fe-cc9cd94ba2e1.png)

**Comment by gbuckholtz** [comment]
I will compare the two branches.

**Comment by gbuckholtz** [comment]
@DanDjuric ,  the two branches are identical:
<img width="1325" alt="Screen Shot 2023-03-17 at 3 52 22 PM" src="https://user-images.githubusercontent.com/1216916/226017354-76a3835d-384b-48d8-b4c4-2b7993a0122c.png">

**Comment by gbuckholtz** [comment]
oops,  if I compare in the OTHER direction there is one [change](https://github.com/Machine-Mavericks/FRC-2023/compare/v2.1...v2.0-LondonComp)

**Comment by gbuckholtz** [comment]
![Screen Shot 2023-03-17 at 4 57 23 PM](https://user-images.githubusercontent.com/1216916/226045048-ef4d6045-fd7a-4c85-a0ec-a12096c025ae.png)

**Comment by gbuckholtz** [comment]
have a new version now: [version 2.2](https://github.com/Machine-Mavericks/FRC-2023/tree/v2.2)

**Comment by gbuckholtz** [comment]
Comp is over!
